export const POSTS_FETCHING_START = 'POSTS_FETCHING_START';
export const POSTS_FETCHING_SUCCESS = 'POSTS_FETCHING_SUCCESS';
export const POSTS_FETCHING_FAILURE = 'POSTS_FETCHING_FAILURE';
export const POSTS_ADD_POST = 'POSTS_ADD_POST';
export const POSTS_DELETE_POST = 'POSTS_DELETE_POST';
export const POSTS_UPDATE_POST = 'POSTS_UPDATE_POST';
