export const COMMENTS_FETCHING_START = 'COMMENTS_FETCHING_START';
export const COMMENTS_FETCHING_SUCCESS = 'COMMENTS_FETCHING_SUCСESS';
export const COMMENTS_FETCHING_FAILURE = 'COMMENTS_FETCHING_FAILURE';
export const COMMENTS_ADD_COMMENT = 'COMMENTS_ADD_COMMENT';
export const COMMENTS_DELETE_COMMENT = 'COMMENTS_DELETE_COMMENT';
export const COMMENTS_UPDATE_COMMENT = 'COMMENTS_UPDATE_COMMENT';
